version: "3.9"
services:
  postgres:
    image: postgres:11-alpine3.16
    networks:
      - backend
    command:
      - "postgres"
      - "-c"
      - "log_line_prefix=%m [%p]  %q%u@%d %h - "
    restart: always
    environment:
      POSTGRES_DB: "pgdb"
      POSTGRES_USER: "pgsql"
      POSTGRES_PASSWORD: "PASS"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  user:
    build: .
    networks:
      - backend
      - frontend
    restart: always
    depends_on:
      - "postgres"
    ports:
      - "8000:8000"
    expose:
      - "8000"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge