version: "3.9"
services:
  userpg:
    image: postgres:11-alpine3.16
    networks:
      - backend
    command:
      - "postgres"
      - "-c"
      - "log_line_prefix=%m [%p]  %q%u@%d %h - "
    environment:
      POSTGRES_DB: "pgdb"
      POSTGRES_USER: "pgsql"
      POSTGRES_PASSWORD: "PASS"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
  user:
    build: .
    networks:
      - backend
      - frontend
    restart: always
    environment:
      JWTkey: "SECRET"
      addr: ":8000"
      PGUser: "pgsql"
      PGPass: "PASS"
      PGAddr: "userpg:5432"
      PGDB: "pgdb"
    depends_on:
      - "userpg"
    ports:
      - "8000:8000"
    expose:
      - "8000"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge